//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cookere
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cookere()
        {
            this.Families = new HashSet<Family>();
        }
    
        public string CookerId { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Phone { get; set; }
        public string FullName { get; set; }
        public Nullable<int> KashroutId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Street { get; set; }
        public Nullable<int> Apartment_number { get; set; }
        public string KindOfFood { get; set; }
        public string driverId { get; set; }
    
        public virtual City City { get; set; }
        public virtual Driver Driver { get; set; }
        public virtual Kashrout Kashrout { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Family> Families { get; set; }
    }
}
