//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Family
    {
        public int Familyid { get; set; }
        public string FamilyName { get; set; }
        public string Phone { get; set; }
        public Nullable<int> CityId { get; set; }
        public string Street { get; set; }
        public Nullable<int> Apartment_number { get; set; }
        public Nullable<int> KashroutId { get; set; }
        public Nullable<int> NumberOfPeople { get; set; }
        public string CookerId { get; set; }
    
        public virtual City City { get; set; }
        public virtual Cookere Cookere { get; set; }
        public virtual Kashrout Kashrout { get; set; }
    }
}
