//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnegShabatEntities : DbContext
    {
        public OnegShabatEntities()
            : base("name=OnegShabatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Cookere> Cookeres { get; set; }
        public virtual DbSet<Donor> Donors { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<Family> Families { get; set; }
        public virtual DbSet<Kashrout> Kashrouts { get; set; }
    }
}
